version: '3'
services:
  redis-master:
    container_name: "redis-master"
    image: redis
    ports:
      - "6379:6379"
    networks:
      - host
    command: "redis-server /etc/redis.conf"
    volumes:
      - "./data/master:/data/"
      - "./master.conf:/etc/redis.conf"
  
  redis-slave:
    container_name: "redis-slave"
    image: redis
    ports:
      - "6380:6379"
    networks:
      - host
    command: "redis-server /etc/redis.conf"
    volumes:
      - "./data/slave:/data/"
      - "./slave.conf:/etc/redis.conf"
    depends_on:
      - redis-master

  redis-slave-2:
    container_name: "redis-slave-2"
    image: redis
    ports:
      - "6381:6379"
    networks:
      - host
    command: "redis-server /etc/redis.conf"
    volumes:
      - "./data/slave:/data/"
      - "./slave.conf:/etc/redis.conf"
    depends_on:
      - redis-master

  redis-sentinel:
    container_name: 'redis-sentinel'
    image: redis
    ports:
      - "26379:26379"
    networks:
      - host
    command: "redis-server /data/sentinel.conf --sentinel"
    volumes:
      - "./data/sentinel_conf:/data/"
    depends_on:
      - redis-master
      - redis-slave

  redis-sentinel-2:
    container_name: 'redis-sentinel-2'
    image: redis
    ports:
      - "26380:26379"
    networks:
      - host
    command: "redis-server /data/sentinel.conf --sentinel"
    volumes:
      - "./data/sentinel_conf:/data/"
    depends_on:
      - redis-master
      - redis-slave

  redis-insight:
    container_name: "redis-insight"
    image: "oblakstudio/redisinsight:latest"
    ports:
      - "5540:5540"
    networks:
      - host
    depends_on:
      - redis-master
      - redis-slave
      - redis-slave-2

  flask-app:
    container_name: "flask-app"
    image: pythonredis
    ports:
      - "8000:8000"
    networks:
      - host
    volumes:
      - "./flask-app:/flask-app"
    depends_on:
      - redis-master
      - redis-slave
      - redis-slave-2

  flask-app-2:
    container_name: "flask-app-2"
    image: pythonredis
    ports:
      - "8001:8000"
    networks:
      - host
    volumes:
      - "./flask-app:/flask-app"
    depends_on:
      - redis-master
      - redis-slave
      - redis-slave-2

  proxy:
    image: haproxy-redis
    depends_on:
      - redis-master
    networks:
      - host
    ports:
      - '8404:8404'
      - '8080:80'

networks:
  host: